- name: variables
  hosts: localhost
  vars:
    COURSE: "ANSIBLE"
    TRAINER: "SIVAKUMAR"
    DURATION: "120HRS"
  tasks:
  - name: print overridden 
    vars:
      COURSE: "DEVOPS"
    ansible.builtin.debug:  
      msg: "Hi we are learning {{COURSE}} from {{TRAINER}}, Duration is {{DURATION}}"
  - name: print information
    ansible.builtin.debug:
      msg: "Hi we are learning {{COURSE}} from {{TRAINER}}, Duration is {{DURATION}}"