- name: data types
  hosts: localhost
  vars:
    COURSE: Devops with AWS #STRING
    Tools: #LIST
    - LINUX
    - SHELL
    - ANSIBLE
    Experience: #MAP/DIRECTORY
      DEVOPS: 3 #NUMBER
      AWS: 2
      DOCKER: 1
    Realproject: true #boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "course :{{COURSE}},Tools Covered :{{Tools}},Experience is:{{Experience}},Real project is:{{Realproject}}"